export const API_ENDPOINTS = {
  LOGIN: "/user/register",
  REGISTER: "/register",
  LOGOUT: "/logout",
  FORGET_PASSWORD: "/forget-password",
  CATEGORIES: "/categories.json",
  FEATURED_CATEGORIES: "/featured_categories.json",
  COLLECTIONS: "/collections.json",
  BRANDS: "/brands.json",
  PRODUCTS: "/products.json",
  FEATURED_PRODUCTS: "/featured_products.json",
  TOP_SELLER_PRODUCTS: "/products_top_seller.json",
  ON_SELLING_PRODUCTS: "/products_on_selling.json",
  PRODUCT: "/product.json",
  RELATED_PRODUCTS: "/related_products.json",
  BEST_SELLER_PRODUCTS: "/products_best_seller.json",
  NEW_ARRIVAL_PRODUCTS: "/products_new_arrival.json",
  FLASH_SALE_PRODUCTS: "/buyer/product-pagination/6QNWB7F/null",
  SEARCH: "/search.json",
  ORDERS: "/orders/:id",
  ORDER: "/order.json",
  CHECKOUT:"/orders/checkout",
  VERIFYPAYMENT:"/orders/verify-payment",
  VERIFYOTP:"/user/verify",
  RESENTOTP:"/user/resendOtp",
  GETUSERCHATTOOMS:"/user/:id"
};
